### ISSUE TITLE
what about collision detection of circles?

### ISSUE THREAD

**Issue by deepaktechno** [nazgee/AndEngineDebugDrawExtension#2]
Hello,

first of all thank you for a great extension of andengine.
i am using your extension to draw a circle around my sprite.
but when i use .collidesWith() method.
there is no response.
could i ask you why?

**Comment by nazgee** [comment]
It is not meant to be used as a regular entity, but if you want to- you can implement the collision method yourself. AFAIK, Mesh::collidesWith() currently returns false all the time now, so that is the reason.
